name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Android'
    labels:
      - 'android'
  - title: 'iOS'
    labels:
      - 'iOS'
  - title: 'Kmm'
    labels:
      - 'kmm'
template: |
  ## What’s Changed

  $CHANGES
